import {
  Award,
  Banknote,
  BarChart3,
  BookOpen,
  Boxes,
  Briefcase,
  Building2,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarOff,
  CircleDollarSign,
  ClipboardList,
  CreditCard,
  Crosshair,
  FileText,
  Flag,
  Gift,
  Globe,
  GraduationCap,
  History,
  HandCoins,
  IdCard,
  Landmark,
  Layers,
  LayoutDashboard,
  LineChart,
  Megaphone,
  NotebookPen,
  Percent,
  Presentation,
  Receipt,
  ReceiptText,
  School,
  Share2,
  ShieldCheck,
  ShoppingCart,
  Ticket,
  TrendingDown,
  Trophy,
  Truck,
  UserCheck,
  UserCircle,
  UserCog,
  Users,
  Wallet,
  Warehouse,
  Wrench,
  PartyPopper,
  Rocket,
  Handshake,
  GraduationCap as InternGraduationCap,
  Contact,
  PartyPopper as AlumniEventIcon,
  Newspaper,
  Images,
  Workflow,
  ListChecks,
  UserCheck2,
  MessageSquare,
  Calendar,
  Database,
  Plug,
  Activity,
} from "lucide-react";

export interface NavItem {
  label: string;
  href: string;
  icon: typeof LayoutDashboard;
  enabled: boolean;
}

export interface NavSection {
  title: string;
  items: NavItem[];
}

export const navSections: NavSection[] = [
  {
    title: "Overview",
    items: [
      { label: "Dashboard", href: "/", icon: LayoutDashboard, enabled: true },
      { label: "Calendar", href: "/events", icon: Calendar, enabled: true },
    ],
  },
  {
    title: "Administration",
    items: [
      { label: "Organizations", href: "/organizations", icon: Building2, enabled: true },
      { label: "Users", href: "/administration/users", icon: IdCard, enabled: true },
      { label: "Roles", href: "/administration/roles", icon: ShieldCheck, enabled: true },
      { label: "Audit Logs", href: "/administration/audit-logs", icon: History, enabled: true },
      { label: "Broadcast Notification", href: "/administration/broadcast", icon: Megaphone, enabled: true },
      { label: "Database Backups", href: "/administration/backups", icon: Database, enabled: true },
      { label: "Integrations", href: "/administration/integrations", icon: Plug, enabled: true },
      { label: "System Health", href: "/administration/monitoring", icon: Activity, enabled: true },
    ],
  },
  {
    title: "Business Modules",
    items: [
      { label: "Leads", href: "/crm/leads", icon: Users, enabled: true },
      { label: "Admissions", href: "/crm/admissions", icon: UserCheck, enabled: true },
      { label: "Students", href: "/students", icon: GraduationCap, enabled: true },
      { label: "Courses", href: "/courses", icon: BookOpen, enabled: true },
      { label: "Batches", href: "/batches", icon: CalendarClock, enabled: true },
      { label: "Trainers", href: "/trainers", icon: Presentation, enabled: true },
      { label: "Classrooms", href: "/classrooms", icon: School, enabled: true },
      { label: "Announcements", href: "/lms/announcements", icon: Megaphone, enabled: true },
      { label: "Badges", href: "/lms/badges", icon: Award, enabled: true },
      { label: "Question Bank", href: "/examinations/question-bank", icon: ClipboardList, enabled: true },
      { label: "Pentrix Labs", href: "/pentrix/labs", icon: Crosshair, enabled: true },
      { label: "Pentrix Challenges", href: "/pentrix/challenges", icon: Flag, enabled: true },
      { label: "Pentrix Leaderboard", href: "/pentrix/leaderboard", icon: Trophy, enabled: true },
      { label: "Pentrix Achievements", href: "/pentrix/achievements", icon: Award, enabled: true },
      { label: "Chart of Accounts", href: "/accounting/ledger", icon: Landmark, enabled: true },
      { label: "Journals", href: "/accounting/journals", icon: NotebookPen, enabled: true },
      { label: "Customers", href: "/accounting/customers", icon: UserCircle, enabled: true },
      { label: "Vendors", href: "/accounting/vendors", icon: Truck, enabled: true },
      { label: "Invoices", href: "/accounting/invoices", icon: FileText, enabled: true },
      { label: "Receipts", href: "/accounting/receipts", icon: Receipt, enabled: true },
      { label: "Expenses", href: "/accounting/expenses", icon: CreditCard, enabled: true },
      { label: "Payments", href: "/accounting/payments", icon: HandCoins, enabled: true },
      { label: "Bank Accounts", href: "/accounting/bank", icon: Banknote, enabled: true },
      { label: "GST", href: "/accounting/gst", icon: Percent, enabled: true },
      { label: "TDS", href: "/accounting/tds", icon: ReceiptText, enabled: true },
      { label: "Financial Reports", href: "/accounting/reports", icon: BarChart3, enabled: true },
      { label: "Employees", href: "/employees", icon: UserCog, enabled: true },
      { label: "Departments & Designations", href: "/hr/departments-designations", icon: Building2, enabled: true },
      { label: "Attendance", href: "/attendance", icon: CalendarCheck, enabled: true },
      { label: "Leave Types", href: "/leave/types", icon: CalendarOff, enabled: true },
      { label: "Leave Applications", href: "/leave/applications", icon: CalendarDays, enabled: true },
      { label: "Salary Components", href: "/payroll/components", icon: Wallet, enabled: true },
      { label: "Payroll Runs", href: "/payroll/runs", icon: CircleDollarSign, enabled: true },
      { label: "Item Categories & Warehouses", href: "/inventory/settings", icon: Warehouse, enabled: true },
      { label: "Inventory Items", href: "/inventory/items", icon: Boxes, enabled: true },
      { label: "Asset Categories", href: "/assets/categories", icon: Layers, enabled: true },
      { label: "Fixed Assets", href: "/assets", icon: Wrench, enabled: true },
      { label: "Depreciation Runs", href: "/assets/depreciation-runs", icon: TrendingDown, enabled: true },
      { label: "Purchase Orders", href: "/procurement/purchase-orders", icon: ShoppingCart, enabled: true },
      { label: "Clients", href: "/corporate/clients", icon: Briefcase, enabled: true },
      { label: "Corporate Reports", href: "/corporate/reports", icon: BarChart3, enabled: true },
      { label: "Campaigns", href: "/marketing/campaigns", icon: Megaphone, enabled: true },
      { label: "Coupons", href: "/marketing/coupons", icon: Ticket, enabled: true },
      { label: "Landing Pages", href: "/marketing/landing-pages", icon: Globe, enabled: true },
      { label: "Referral Programs", href: "/marketing/referrals/programs", icon: Gift, enabled: true },
      { label: "Referrals", href: "/marketing/referrals", icon: Share2, enabled: true },
      { label: "Marketing Overview", href: "/marketing/analytics", icon: LineChart, enabled: true },
      { label: "Workshops", href: "/workshops", icon: PartyPopper, enabled: true },
      { label: "Hackathons", href: "/hackathons", icon: Rocket, enabled: true },
      { label: "Placement Companies", href: "/placements/companies", icon: Building2, enabled: true },
      { label: "Job Postings", href: "/placements/postings", icon: Handshake, enabled: true },
      { label: "Internship Postings", href: "/internships/postings", icon: InternGraduationCap, enabled: true },
      { label: "Active Internships", href: "/internships", icon: ClipboardList, enabled: true },
      { label: "Alumni Profiles", href: "/alumni/profiles", icon: Contact, enabled: true },
      { label: "Alumni Events", href: "/alumni/events", icon: AlumniEventIcon, enabled: true },
      { label: "Job Referrals", href: "/alumni/referrals", icon: Newspaper, enabled: true },
      { label: "Media Gallery", href: "/media/albums", icon: Images, enabled: true },
      { label: "Communication Log", href: "/communication/logs", icon: MessageSquare, enabled: true },
      { label: "Approval Workflows", href: "/workflow/workflows", icon: Workflow, enabled: true },
      { label: "Approval Requests", href: "/workflow/requests", icon: ListChecks, enabled: true },
      { label: "My Approvals", href: "/workflow/my-approvals", icon: UserCheck2, enabled: true },
    ],
  },
];
