"""
CRM / Leads — ORM models.

`Lead` is the entry point of the CRM pipeline: raw contact interest,
scoped to an organization (and optionally a branch). Enquiries,
FollowUps, Counselling sessions, and the eventual Admission all hang
off a Lead by foreign key. `campaign_id` is an optional attribution
link to `modules.marketing.campaigns.Campaign` — set when a lead was
generated by a specific marketing campaign, so Marketing's analytics
can roll up leads-generated per campaign without CRM needing to know
anything about Marketing beyond this one nullable FK.
"""

import enum
import uuid

from sqlalchemy import ForeignKey, String, Text
from sqlalchemy import Enum as SAEnum
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base_model import SoftDeleteMixin, TimestampedBase
from modules.organizations.models import Organization  # noqa: F401
from modules.branches.models import Branch  # noqa: F401
from modules.authentication.models import User  # noqa: F401


class LeadSource(str, enum.Enum):
    WEBSITE = "website"
    REFERRAL = "referral"
    SOCIAL_MEDIA = "social_media"
    WALK_IN = "walk_in"
    ADVERTISEMENT = "advertisement"
    EVENT = "event"
    OTHER = "other"


class LeadStatus(str, enum.Enum):
    NEW = "new"
    CONTACTED = "contacted"
    QUALIFIED = "qualified"
    CONVERTED = "converted"
    LOST = "lost"


def _values(enum_cls):
    return [m.value for m in enum_cls]


class Lead(TimestampedBase, SoftDeleteMixin):
    __tablename__ = "crm_leads"

    organization_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    branch_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("branches.id", ondelete="SET NULL"), nullable=True, index=True
    )
    campaign_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("marketing_campaigns.id", ondelete="SET NULL"), nullable=True, index=True
    )

    full_name: Mapped[str] = mapped_column(String(255), nullable=False)
    email: Mapped[str | None] = mapped_column(String(255), nullable=True)
    phone: Mapped[str | None] = mapped_column(String(32), nullable=True)

    source: Mapped[LeadSource] = mapped_column(
        SAEnum(LeadSource, name="lead_source", values_callable=_values),
        default=LeadSource.OTHER,
        server_default=LeadSource.OTHER.value,
        nullable=False,
    )
    status: Mapped[LeadStatus] = mapped_column(
        SAEnum(LeadStatus, name="lead_status", values_callable=_values),
        default=LeadStatus.NEW,
        server_default=LeadStatus.NEW.value,
        nullable=False,
        index=True,
    )

    assigned_to_user_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True
    )
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    lost_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
